export const deniedClaims = [
  {
    id: 202505100009,
    claimant: "John Doe",
    amount: "$1,040.00",
    date: "2025-05-10",
    status: "Denied",
    denialCode: "CO‑16",
    denialReason: "Claim/service lacks information – clinical notes missing.",
    description: "Outpatient consultation for fever and malaise.",
    provider: "Dr. Angela Smith",
    providerNPI: "1234567890",
    serviceType: "Outpatient Professional",
    serviceDate: "2025-05-09",
    documentationList: [
      { name: "Discharge Summary.pdf", type: "PDF Document", url: "#" },
      { name: "LabReport_2025-05-01.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505110010,
    claimant: "Maria Gomez",
    amount: "$3,275.00",
    date: "2025-05-11",
    status: "Denied",
    denialCode: "CO‑109",
    denialReason: "Service not covered by this payer/plan.",
    description: "Dental implant placement (single tooth).",
    provider: "Dr. Carlos Navarro",
    providerNPI: "2345678901",
    serviceType: "Dental",
    serviceDate: "2025-05-10",
    documentationList: [
      { name: "Implant Invoice.pdf", type: "PDF Document", url: "#" },
      { name: "Panoramic X‑ray.jpg", type: "Image", url: "#" },
    ],
  },
  {
    id: 202505120011,
    claimant: "Elena Petrova",
    amount: "$520.00",
    date: "2025-05-12",
    status: "Denied",
    denialCode: "CO‑97",
    denialReason: "Patient ineligible for service on date of service.",
    description: "Physical therapy follow‑up session (post‑op shoulder).",
    provider: "Dr. Henry Wu",
    providerNPI: "3456789012",
    serviceType: "Outpatient Rehabilitation",
    serviceDate: "2025-05-11",
    documentationList: [
      { name: "Therapy Notes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505130012,
    claimant: "Ahmed Khan",
    amount: "$1,895.00",
    date: "2025-05-13",
    status: "Denied",
    denialCode: "CO‑50",
    denialReason: "These are non‑covered services because this is not deemed a medical necessity by the payer.",
    description: "Sleep study (polysomnography) without prior authorization.",
    provider: "Dr. Laura Green",
    providerNPI: "4567890123",
    serviceType: "Diagnostic",
    serviceDate: "2025-05-12",
    documentationList: [
      { name: "Sleep Study Report.pdf", type: "PDF Document", url: "#" },
      { name: "PriorAuthForm.pdf", type: "PDF Document", url: "#" },
    ],
  },
];