export const deniedClaims = [
 
  {
    id: 202505130012,
    claimant: "Ahmed Khan",
    amount: "$1,895.00",
    date: "2025-05-13",
    status: "Denied",
    denialCode: "CO-50",
    denialReason:
      "These are non-covered services because this is not deemed a medical necessity by the payer.",
    description: "Sleep study (polysomnography) without prior authorization.",
    provider: "Dr. Laura Green",
    providerNPI: "4567890123",
    serviceType: "Diagnostic",
    serviceDate: "2025-05-12",
    documentationList: [
      { name: "Sleep Study Report.pdf", type: "PDF Document", url: "#" },
      { name: "PriorAuthForm.pdf", type: "PDF Document", url: "#" },
    ],
  },

  /* ──── +25 new rows (some Approved) ──── */
  {
    id: 202505140013,
    claimant: "Denise Liu",
    amount: "$2,350.00",
    date: "2025-05-14",
    status: "Denied",
    denialCode: "CO-16",
    denialReason: "Missing operative report.",
    description: "Laparoscopic appendectomy – operative claim.",
    provider: "Dr. Samuel Park",
    providerNPI: "5678901234",
    serviceType: "Inpatient Surgical",
    serviceDate: "2025-05-13",
    documentationList: [
      { name: "OpReport.pdf", type: "PDF Document", url: "#" },
      { name: "ConsentForm.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505150014,
    claimant: "Robert Kim",
    amount: "$780.00",
    date: "2025-05-15",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Follow-up dermatology visit for eczema management.",
    provider: "Dr. Linda Chen",
    providerNPI: "6789012345",
    serviceType: "Outpatient Professional",
    serviceDate: "2025-05-14",
    documentationList: [
      { name: "DermVisitNotes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505160015,
    claimant: "Priya Patel",
    amount: "$4,500.00",
    date: "2025-05-16",
    status: "Denied",
    denialCode: "CO-109",
    denialReason: "Procedure not covered—cosmetic rhinoplasty.",
    description: "Elective cosmetic rhinoplasty.",
    provider: "Dr. Javier Morales",
    providerNPI: "7890123456",
    serviceType: "Outpatient Surgical",
    serviceDate: "2025-05-15",
    documentationList: [
      { name: "SurgicalEstimate.pdf", type: "PDF Document", url: "#" },
      { name: "PreOpPhotos.jpg", type: "Image", url: "#" },
    ],
  },
  {
    id: 202505170016,
    claimant: "Miguel Sanchez",
    amount: "$1,250.00",
    date: "2025-05-17",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Emergency department visit – chest pain workup.",
    provider: "Dr. Olivia Brooks",
    providerNPI: "8901234567",
    serviceType: "Emergency",
    serviceDate: "2025-05-17",
    documentationList: [
      { name: "EDChart.pdf", type: "PDF Document", url: "#" },
      { name: "ECG_2025-05-17.png", type: "Image", url: "#" },
    ],
  },
  {
    id: 202505180017,
    claimant: "Fatima Al-Zahrani",
    amount: "$310.00",
    date: "2025-05-18",
    status: "Denied",
    denialCode: "CO-96",
    denialReason: "Non-covered routine vision exam.",
    description: "Annual vision exam and refraction.",
    provider: "Dr. Kevin Lee",
    providerNPI: "9012345678",
    serviceType: "Vision",
    serviceDate: "2025-05-18",
    documentationList: [
      { name: "VisionExam.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505190018,
    claimant: "Lucas Moreau",
    amount: "$6,890.00",
    date: "2025-05-19",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Inpatient admission for acute pancreatitis (3 days).",
    provider: "Dr. Hannah Dupont",
    providerNPI: "0123456789",
    serviceType: "Inpatient Hospital",
    serviceDate: "2025-05-16",
    documentationList: [
      { name: "DischargeSummary.pdf", type: "PDF Document", url: "#" },
      { name: "Imaging_CT_Abdomen.jpg", type: "Image", url: "#" },
    ],
  },
  {
    id: 202505200019,
    claimant: "Hannah Choi",
    amount: "$945.00",
    date: "2025-05-20",
    status: "Denied",
    denialCode: "CO-15",
    denialReason: "Authorization number missing or invalid.",
    description: "MRI knee with contrast.",
    provider: "Dr. Robert Young",
    providerNPI: "1122334455",
    serviceType: "Diagnostic",
    serviceDate: "2025-05-19",
    documentationList: [
      { name: "MRI_Knee_Order.pdf", type: "PDF Document", url: "#" },
      { name: "PriorAuthRequest.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505210020,
    claimant: "Ivan Ivanov",
    amount: "$420.00",
    date: "2025-05-21",
    status: "Denied",
    denialCode: "CO-97",
    denialReason: "Patient not eligible on date of service.",
    description: "Chiropractic adjustment—lumbar region.",
    provider: "Dr. Karen Smith",
    providerNPI: "1223344556",
    serviceType: "Chiropractic",
    serviceDate: "2025-05-20",
    documentationList: [
      { name: "ChiroNotes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505220021,
    claimant: "Sophie Turner",
    amount: "$230.00",
    date: "2025-05-22",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Routine prenatal visit (24-week).",
    provider: "Dr. Grace Patel",
    providerNPI: "1334455667",
    serviceType: "Obstetrics",
    serviceDate: "2025-05-22",
    documentationList: [
      { name: "PrenatalNotes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505230022,
    claimant: "Chen Wei",
    amount: "$2,160.00",
    date: "2025-05-23",
    status: "Denied",
    denialCode: "CO-16",
    denialReason: "Operative report incomplete.",
    description: "Anterior cruciate ligament reconstruction.",
    provider: "Dr. Marco Rossi",
    providerNPI: "1445566778",
    serviceType: "Outpatient Surgical",
    serviceDate: "2025-05-22",
    documentationList: [
      { name: "ACL_OpReport.pdf", type: "PDF Document", url: "#" },
      { name: "AnesthesiaRecord.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505240023,
    claimant: "Peter Johnson",
    amount: "$135.00",
    date: "2025-05-24",
    status: "Denied",
    denialCode: "CO-173",
    denialReason: "Service cancelled by patient.",
    description: "Telehealth consult—URI symptoms.",
    provider: "Dr. Alicia Nguyen",
    providerNPI: "1556677889",
    serviceType: "Telehealth",
    serviceDate: "2025-05-24",
    documentationList: [{ name: "TeleVisit.mp4", type: "Video", url: "#" }],
  },
  {
    id: 202505250024,
    claimant: "Olga Smirnova",
    amount: "$560.00",
    date: "2025-05-25",
    status: "Denied",
    denialCode: "CO-96",
    denialReason: "Routine dental cleaning not covered.",
    description: "Prophylaxis & bite-wing X-rays.",
    provider: "Dr. Paul Hernandez",
    providerNPI: "1667788990",
    serviceType: "Dental",
    serviceDate: "2025-05-25",
    documentationList: [
      { name: "DentalChart.pdf", type: "PDF Document", url: "#" },
      { name: "XRay_BiteWing.jpg", type: "Image", url: "#" },
    ],
  },
  {
    id: 202505260025,
    claimant: "Mohammed Ali",
    amount: "$3,200.00",
    date: "2025-05-26",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Cardiac catheterization with stent placement.",
    provider: "Dr. Sarah Johnson",
    providerNPI: "1778899001",
    serviceType: "Cardiology",
    serviceDate: "2025-05-24",
    documentationList: [
      { name: "CathLabReport.pdf", type: "PDF Document", url: "#" },
      { name: "AngioImages.zip", type: "Archive", url: "#" },
    ],
  },
  {
    id: 202505270026,
    claimant: "Julia Bianchi",
    amount: "$480.00",
    date: "2025-05-27",
    status: "Denied",
    denialCode: "CO-50",
    denialReason: "Medical necessity not met—overnight oximetry.",
    description: "At-home overnight pulse oximetry.",
    provider: "Dr. James Carter",
    providerNPI: "1889900112",
    serviceType: "Diagnostic",
    serviceDate: "2025-05-26",
    documentationList: [
      { name: "OximetryReport.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505280027,
    claimant: "David Brown",
    amount: "$2,975.00",
    date: "2025-05-28",
    status: "Denied",
    denialCode: "CO-45",
    denialReason: "Charge exceeds contracted fee schedule.",
    description: "Endoscopic sinus surgery (bilateral).",
    provider: "Dr. Teresa Mendoza",
    providerNPI: "1990011223",
    serviceType: "Outpatient Surgical",
    serviceDate: "2025-05-27",
    documentationList: [
      { name: "ESS_OpNotes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505290028,
    claimant: "Aiko Tanaka",
    amount: "$610.00",
    date: "2025-05-29",
    status: "Denied",
    denialCode: "CO-97",
    denialReason: "Coverage lapsed prior to DOS.",
    description: "Post-op orthopedic follow-up visit.",
    provider: "Dr. Victor Huang",
    providerNPI: "2001122334",
    serviceType: "Outpatient Professional",
    serviceDate: "2025-05-29",
    documentationList: [
      { name: "FollowUpNotes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505300029,
    claimant: "Carlos Silva",
    amount: "$7,450.00",
    date: "2025-05-30",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Total hip arthroplasty (left).",
    provider: "Dr. Ellen Fischer",
    providerNPI: "2112233445",
    serviceType: "Inpatient Surgical",
    serviceDate: "2025-05-28",
    documentationList: [
      { name: "SurgerySummary.pdf", type: "PDF Document", url: "#" },
      { name: "ImplantInvoice.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505310030,
    claimant: "Greta Lund",
    amount: "$155.00",
    date: "2025-05-31",
    status: "Denied",
    denialCode: "CO-18",
    denialReason: "Duplicate claim/service.",
    description: "Routine blood draw—CBC & CMP.",
    provider: "Dr. Daniel Kim",
    providerNPI: "2223344556",
    serviceType: "Laboratory",
    serviceDate: "2025-05-30",
    documentationList: [
      { name: "LabOrder.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202506010031,
    claimant: "Nikhil Rao",
    amount: "$870.00",
    date: "2025-06-01",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Gastroenterology consult—GERD evaluation.",
    provider: "Dr. Monica Alvarez",
    providerNPI: "2334455667",
    serviceType: "Outpatient Professional",
    serviceDate: "2025-05-31",
    documentationList: [
      { name: "ConsultNotes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202506020032,
    claimant: "Patricia Lopez",
    amount: "$5,230.00",
    date: "2025-06-02",
    status: "Denied",
    denialCode: "CO-15",
    denialReason: "Authorization expired before service.",
    description: "Robotic hysterectomy.",
    provider: "Dr. Richard O'Neil",
    providerNPI: "2445566778",
    serviceType: "Inpatient Surgical",
    serviceDate: "2025-06-01",
    documentationList: [
      { name: "PreOpClearance.pdf", type: "PDF Document", url: "#" },
      { name: "PathologyRequest.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202506030033,
    claimant: "Ahmed Hassan",
    amount: "$260.00",
    date: "2025-06-03",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Physical therapy session—knee rehab.",
    provider: "Dr. Emily Stone",
    providerNPI: "2556677889",
    serviceType: "Outpatient Rehabilitation",
    serviceDate: "2025-06-02",
    documentationList: [
      { name: "PT_Notes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202506040034,
    claimant: "Emily Davis",
    amount: "$340.00",
    date: "2025-06-04",
    status: "Denied",
    denialCode: "CO-96",
    denialReason: "Routine podiatry care not covered.",
    description: "Toenail debridement—routine foot care.",
    provider: "Dr. Oscar Perez",
    providerNPI: "2667788990",
    serviceType: "Podiatry",
    serviceDate: "2025-06-04",
    documentationList: [
      { name: "PodiatryNotes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202506050035,
    claimant: "Stefano Romano",
    amount: "$980.00",
    date: "2025-06-05",
    status: "Approved",
    denialCode: null,
    denialReason: null,
    description: "Neurology follow-up—migraine management.",
    provider: "Dr. Karen Lee",
    providerNPI: "2778899001",
    serviceType: "Outpatient Professional",
    serviceDate: "2025-06-04",
    documentationList: [
      { name: "NeuroNotes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202506060036,
    claimant: "Chloe Nguyen",
    amount: "$2,410.00",
    date: "2025-06-06",
    status: "Denied",
    denialCode: "CO-50",
    denialReason: "Experimental procedure not covered.",
    description: "Platelet-rich plasma (PRP) shoulder injection.",
    provider: "Dr. Steven Clark",
    providerNPI: "2889900112",
    serviceType: "Therapeutic Injection",
    serviceDate: "2025-06-05",
    documentationList: [
      { name: "PRP_Consent.pdf", type: "PDF Document", url: "#" },
      { name: "UltrasoundGuide.jpg", type: "Image", url: "#" },
    ],
  },
  {
    id: 202506070037,
    claimant: "George Miller",
    amount: "$315.00",
    date: "2025-06-07",
    status: "Denied",
    denialCode: "CO-16",
    denialReason: "Clinical documentation incomplete—radiology report missing.",
    description: "Chest X-ray—two views, initial.",
    provider: "Dr. Laura Anderson",
    providerNPI: "2990011223",
    serviceType: "Diagnostic",
    serviceDate: "2025-06-07",
    documentationList: [
      { name: "XRayOrder.pdf", type: "PDF Document", url: "#" },
    ],
  },
   {
    id: 202505100001,
    claimant: "John Doe",
    amount: "$1,040.00",
    date: "2025-05-10",
    status: "Denied",
    denialCode: "CO‑16",
    denialReason: "Claim/service lacks information – clinical notes missing.",
    description: "Outpatient consultation for fever and malaise.",
    provider: "Dr. Angela Smith",
    providerNPI: "1234567890",
    serviceType: "Outpatient Professional",
    serviceDate: "2025-05-09",
    documentationList: [
      { name: "Discharge Summary.pdf", type: "PDF Document", url: "#" },
      { name: "LabReport_2025-05-01.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 20250511002,
    claimant: "Maria Gomez",
    amount: "$3,275.00",
    date: "2025-05-11",
    status: "Denied",
    denialCode: "CO‑109",
    denialReason: "Service not covered by this payer/plan.",
    description: "Dental implant placement (single tooth).",
    provider: "Dr. Carlos Navarro",
    providerNPI: "2345678901",
    serviceType: "Dental",
    serviceDate: "2025-05-10",
    documentationList: [
      { name: "Implant Invoice.pdf", type: "PDF Document", url: "#" },
      { name: "Panoramic X‑ray.jpg", type: "Image", url: "#" },
    ],
  },
  {
    id: 20250512003,
    claimant: "Elena Petrova",
    amount: "$520.00",
    date: "2025-05-12",
    status: "Denied",
    denialCode: "CO‑97",
    denialReason: "Patient ineligible for service on date of service.",
    description: "Physical therapy follow‑up session (post‑op shoulder).",
    provider: "Dr. Henry Wu",
    providerNPI: "3456789012",
    serviceType: "Outpatient Rehabilitation",
    serviceDate: "2025-05-11",
    documentationList: [
      { name: "Therapy Notes.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 20250513004,
    claimant: "Ahmed Khan",
    amount: "$1,895.00",
    date: "2025-05-13",
    status: "Denied",
    denialCode: "CO‑50",
    denialReason:
      "These are non‑covered services because this is not deemed a medical necessity by the payer.",
    description: "Sleep study (polysomnography) without prior authorization.",
    provider: "Dr. Laura Green",
    providerNPI: "4567890123",
    serviceType: "Diagnostic",
    serviceDate: "2025-05-12",
    documentationList: [
      { name: "Sleep Study Report.pdf", type: "PDF Document", url: "#" },
      { name: "PriorAuthForm.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505100009,
    claimant: "John Doe",
    amount: "$1,040.00",
    date: "2025-05-10",
    status: "Denied",
    denialCode: "CO-16",
    denialReason: "Claim/service lacks information – clinical notes missing.",
    description: "Outpatient consultation for fever and malaise.",
    provider: "Dr. Angela Smith",
    providerNPI: "1234567890",
    serviceType: "Outpatient Professional",
    serviceDate: "2025-05-09",
    documentationList: [
      { name: "Discharge Summary.pdf", type: "PDF Document", url: "#" },
      { name: "LabReport_2025-05-01.pdf", type: "PDF Document", url: "#" },
    ],
  },
  {
    id: 202505110010,
    claimant: "Maria Gomez",
    amount: "$3,275.00",
    date: "2025-05-11",
    status: "Denied",
    denialCode: "CO-109",
    denialReason: "Service not covered by this payer/plan.",
    description: "Dental implant placement (single tooth).",
    provider: "Dr. Carlos Navarro",
    providerNPI: "2345678901",
    serviceType: "Dental",
    serviceDate: "2025-05-10",
    documentationList: [
      { name: "Implant Invoice.pdf", type: "PDF Document", url: "#" },
      { name: "Panoramic X-ray.jpg", type: "Image", url: "#" },
    ],
  },
  {
    id: 202505120011,
    claimant: "Elena Petrova",
    amount: "$520.00",
    date: "2025-05-12",
    status: "Denied",
    denialCode: "CO-97",
    denialReason: "Patient ineligible for service on date of service.",
    description: "Physical therapy follow-up session (post-op shoulder).",
    provider: "Dr. Henry Wu",
    providerNPI: "3456789012",
    serviceType: "Outpatient Rehabilitation",
    serviceDate: "2025-05-11",
    documentationList: [
      { name: "Therapy Notes.pdf", type: "PDF Document", url: "#" },
    ],
  },
];
